steps:
  # Step 0: Generate dynamic version tag
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Generate Version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION_TAG="v-$(date +%Y%m%d-%H%M%S)"
        echo "VERSION_TAG=$$VERSION_TAG" > /workspace/version.env
        echo "Generated version: $$VERSION_TAG"

  # Step 1: Dynamically create startup.sh
  - name: 'ubuntu'
    id: 'Create startup.sh'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        cat <<EOF > /workspace/startup-$$VERSION_TAG.sh
        #!/bin/bash
        echo "Dynamic startup script for $$VERSION_TAG started..."

        apt-get update -y
        apt-get install -y apache2

        systemctl start apache2
        systemctl enable apache2

        echo "<h1>Apache2 running from version $$VERSION_TAG</h1>" > /var/www/html/index.html
        EOF

        chmod +x /workspace/startup-$$VERSION_TAG.sh

  # Step 2: Upload startup.sh to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Upload startup.sh to GCS'
    args:
      - cp
      - /workspace/startup-$(cat /workspace/version.env | cut -d '=' -f 2).sh
      - gs://vamsi-artifact-bucket/scripts/

  # Step 3: Create Instance Template with startup-script-url
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Instance Template'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        VERSION=$$VERSION_TAG
        STARTUP_SCRIPT_URL=gs://vamsi-artifact-bucket/scripts/startup-$$VERSION.sh

        gcloud compute instance-templates create vamsi-template-$$VERSION \
          --machine-type=e2-medium \
          --region=asia-east1 \
          --image-family=debian-12 \
          --image-project=debian-cloud \
          --tags=http-server,https-server,allow-8080 \
          --metadata=startup-script-url=$$STARTUP_SCRIPT_URL

  # Step 4: Update MIG with new instance template
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Update MIG Only'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        echo "Updating MIG with new template..."
        gcloud compute instance-groups managed set-instance-template vamsi-mig \
          --template=vamsi-template-$$VERSION_TAG \
          --zone=asia-east1-b

        gcloud compute instance-groups managed rolling-action restart vamsi-mig \
          --zone=asia-east1-b

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
