steps:
  # Step 0: Generate dynamic version tag
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Generate Version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION_TAG="v-$(date +%Y%m%d-%H%M%S)"
        echo "VERSION_TAG=$$VERSION_TAG" > /workspace/version.env
        echo "Generated version: $$VERSION_TAG"

  # Step 1: Dynamically create startup.sh (inline Ubuntu)
  - name: 'ubuntu'
    id: 'Create startup.sh'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        FILENAME=/workspace/startup-$$VERSION_TAG.sh
        echo "#!/bin/bash" > $$FILENAME
        echo "echo \"Dynamic startup script for $$VERSION_TAG started...\"" >> $$FILENAME
        echo "apt-get update -y" >> $$FILENAME
        echo "apt-get install -y apache2" >> $$FILENAME
        echo "systemctl start apache2" >> $$FILENAME
        echo "systemctl enable apache2" >> $$FILENAME
        echo "echo \"<h1>Hello Apache2 running from version $$VERSION_TAG</h1>\" > /var/www/html/index.html" >> $$FILENAME
        chmod +x $$FILENAME

  # Step 2: Upload startup.sh to GCS with version tag in filename
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'Upload startup.sh to GCS'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        gsutil cp /workspace/startup-$$VERSION_TAG.sh gs://vamsi-artifact-bucket/scripts/startup-$$VERSION_TAG.sh

  # Step 3: Create Instance Template with startup-script-url (Ubuntu image)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Instance Template'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        VERSION=$$VERSION_TAG
        STARTUP_SCRIPT_URL=gs://vamsi-artifact-bucket/scripts/startup-$$VERSION.sh

        gcloud compute instance-templates create vamsi-template-$$VERSION \
          --machine-type=e2-medium \
          --region=asia-east1 \
          --image-family=ubuntu-2204-lts \
          --image-project=ubuntu-os-cloud \
          --tags=http-server,https-server,allow-8080 \
          --metadata=startup-script-url=$$STARTUP_SCRIPT_URL

  # Step 4: Create or Update MIG with proper if-fi block
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create or Update MIG'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -x
        source /workspace/version.env
        MIG_NAME="vamsi-mig"
        TEMPLATE_NAME="vamsi-template-$$VERSION_TAG"
        ZONE="asia-east1-b"

        echo "Checking if MIG $$MIG_NAME exists..."
        if ! gcloud compute instance-groups managed describe $$MIG_NAME --zone=$$ZONE > /dev/null 2>&1; then
          echo "Creating new MIG with template $$TEMPLATE_NAME"
          gcloud compute instance-groups managed create $$MIG_NAME \
            --base-instance-name=vamsi-instance \
            --template=$$TEMPLATE_NAME \
            --size=1 \
            --zone=$$ZONE
        else
          echo "MIG exists. Updating template to $$TEMPLATE_NAME"
          gcloud compute instance-groups managed set-instance-template $$MIG_NAME \
            --template=$$TEMPLATE_NAME \
            --zone=$$ZONE

          echo "Triggering rolling restart..."
          gcloud compute instance-groups managed rolling-action restart $$MIG_NAME \
            --zone=$$ZONE
        fi

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
